artifact_root: Artifacts

data_ingestion:
  root_dir: Artifacts/data_ingestion
  source_URL: https://github.com/OwusuBlessing/Text-Summarization-Project/raw/master/samsum_dataset-20231120T200002Z-001.zip
  local_data_file: Artifacts/data_ingestion/data.zip
  unzip_dir: Artifacts/data_ingestion

data_validation:
  root_dir: Artifacts/data_validation
  STATUS_FILE: Artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train","test","validation"]

data_transformation:
  root_dir: Artifacts/data_transformation
  data_path: Artifacts/data_ingestion/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail

model_trainer:
  root_dir: Artifacts/model_trainer
  data_path: Artifacts/data_transformation/samsum_dataset
  model_ckpt: google/pegasus-cnn_dailymail

model_evaluation:
  root_dir: Artifacts/model_evaluation
  data_path: Artifacts/data_transformation/samsum_dataset
  model_path: Artifacts/model_trainer/pegasus-samsum-model
  tokenizer_path: Artifacts/model_trainer/tokenizer
  metric_file_name: Artifacts/model_evaluation/metrics.csv






